//! # D-Bus interface proxy for: `com.canonical.dbusmenu`
//!
//! This code was generated by `zbus-xmlgen` `5.3.1` from D-Bus introspection data.
//! Source: `dbusmenu.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PeerProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(interface = "com.canonical.dbusmenu", assume_defaults = true)]
pub trait dbusmenu {
    /// AboutToShow method
    fn about_to_show(&self, id: i32) -> zbus::Result<bool>;

    /// Event method
    fn event(
        &self,
        id: i32,
        eventId: &str,
        data: &zbus::zvariant::Value<'_>,
        timestamp: u32,
    ) -> zbus::Result<()>;

    /// GetGroupProperties method
    fn get_group_properties(
        &self,
        ids: &[i32],
        propertyNames: &[&str],
    ) -> zbus::Result<
        Vec<(
            i32,
            std::collections::HashMap<String, zbus::zvariant::OwnedValue>,
        )>,
    >;

    /// GetLayout method
    fn get_layout(
        &self,
        parentId: i32,
        recursionDepth: i32,
        propertyNames: &[&str],
    ) -> zbus::Result<(
        u32,
        (
            i32,
            std::collections::HashMap<String, zbus::zvariant::OwnedValue>,
            Vec<zbus::zvariant::OwnedValue>,
        ),
    )>;

    /// GetProperty method
    fn get_property(&self, id: i32, property: &str) -> zbus::Result<zbus::zvariant::OwnedValue>;

    /// ItemActivationRequested signal
    #[zbus(signal)]
    fn item_activation_requested(&self, id: i32, timeStamp: u32) -> zbus::Result<()>;

    /// ItemsPropertiesUpdated signal
    #[zbus(signal)]
    fn items_properties_updated(
        &self,
        arg_1: Vec<(
            i32,
            std::collections::HashMap<&str, zbus::zvariant::Value<'_>>,
        )>,
        arg_2: Vec<(i32, Vec<&str>)>,
    ) -> zbus::Result<()>;

    /// LayoutUpdated signal
    #[zbus(signal)]
    fn layout_updated(&self, revision: u32, parentId: i32) -> zbus::Result<()>;

    /// Status property
    #[zbus(property)]
    fn status(&self) -> zbus::Result<String>;

    /// Version property
    #[zbus(property)]
    fn version(&self) -> zbus::Result<u32>;
}
